app = "shiller-server"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

[deploy]
  release_command = "npm run migrate:up"
